### ISSUE TITLE
INTERNAL ERROR

### ISSUE THREAD

**Issue by gzvincen** [java-decompiler/jd-gui#197] opened 2018-02-08 08:11 UTC
when open class file, then display
// INTERNAL ERROR //
[https://github.com/gzvincen/test/blob/master/error.jpg](https://github.com/gzvincen/test/blob/master/error.jpg)
[https://github.com/gzvincen/test/blob/master/imanager-all-9.1.0-2060.jar](https://github.com/gzvincen/test/blob/master/imanager-all-9.1.0-2060.jar)

**Comment by gzvincen** [comment] 2018-02-08 08:14
i use [https://github.com/deathmarine/Luyten/releases/tag/v0.5.3](https://github.com/deathmarine/Luyten/releases/tag/v0.5.3)  it can open my jar file

like this 
[https://github.com/gzvincen/test/blob/master/luyten.jpg](https://github.com/gzvincen/test/blob/master/luyten.jpg)

**Comment by stefan123t** [comment] 2019-05-14 17:01
Same problem here with the new jd-gui 1.43

While jd-gui 1.41 with the jd-core 1.0.0 preview actually worked and improved resulting code considerably over luyten and other decompilers results. 
Problem is that jd-gui 1.4.1 does not allow copying the 1.0.0 output, only 0.7.1 comparison results can be copied.

Is there a way to call the jd-core 1.0.0 library in the jd-gui 1.4.1 directly ?
I tried something like the following without success.
$JAVA_HOME/java -jar jd-gui-1.4.1-jd-core-1.0.0-preview-20190315/ext/jd-core-1.0.0-preview.jar com/lowagie/text/pdf/PdfReader.java

**Comment by stefan123t** [comment] 2019-05-14 17:10
Actually I suppose this can be attributed to #93 and maybe #90, as the class in Question makes uses of inner classes.

**Comment by java-decompiler** [comment] 2019-05-14 21:59
Hi, JD-GUI 1.4.3 replace the old JD-Core 0.7.1 with the (rewrite from scratch) new JD-Core 1.0.0. Try it : it solve this issue.

**Comment by stefan123t** [comment] 2019-05-20 09:33
Hi @java-decompiler,
thanks for your fast response, much appreciated!
I have had positive results with your preview jd-gui-1.4.1 in many cases. But the now available jd-gui 1.4.3 is showing the INTERNAL-ERROR as reported by gzvincen and other bug reporters. I guess it may have something to do with internal classes, as the classes failing with INTERNAL ERROR also have internal classes in my case.
* JD-GUI 1.4.1 works both with jd-core 1.0.0-preview (right) and jd-core-0.7.1 (left in the side-by-side view).
* JD-GUI 1.4.3 does show INTERNAL ERROR with jd-core-1.0.0 final version for a lot but not all classes.

**Comment by stefan123t** [comment] 2019-05-20 09:35
I just tried JD-GUI 1.5.0 with no success either for the PdfReader.class from a 2.0.2 iText library I am trying to decompile.
* JD-GUI 1.5.0 does show INTERNAL ERROR with jd-core 1.0.1

**Comment by emmanue1** [comment] 2019-05-20 11:53
@gzvincen : JD-Core 1.0.+ have a problem with Lambda expression in PowerfulDockerImpl => I'll take a look.
@stefan123t : NPE throws by JD-GUI caused by a bug in JD-Core-1.0.+ on a anonymous inner class => I'll take a look.

**Comment by emmanue1** [comment] 2019-05-20 20:53
Fixed in JD-Core : https://github.com/java-decompiler/jd-core/commit/ca0e165a9ae29ee3b8f8d66155aaab4a4900adba

**Closed by emmanue1** 2019-05-20 20:53 UTC

**Comment by stefan123t** [comment] 2019-05-21 08:55
@emmanue1: Thanks for this really quick and working fix.
This is an unrivalled resolution time!
I have built the latest jd-core trunk with the Commit java-decompiler/jd-core@ca0e165 and it fixed the problem with my PdfReader.class
Many thanks for your outstanding support!
