### ISSUE TITLE
Class names not supported by Windows

### ISSUE THREAD

**Issue by Deltaxel** [java-decompiler/jd-gui#115] opened 2016-02-25 09:02 UTC
Hi,

The generated class names (dVW, fEd, ...) aren't supported by Windows when extracted from the jar file.
Some names are considered as the same on Microsoft OS (ex: dVW & dvw) which make impossible to extract them in the same directory without loosing some of them.

It would be good if an option in preference permitted to have names only in lower case for Windows support.

**Comment by rkraneis** [comment] 2016-04-22 07:08
Hi @Deltaxel,

I believe this is a problem caused by an obfuscator used on the original sources. I do not think that there is much jd can do in this respect.

**Comment by emmanue1** [comment] 2019-05-22 11:54
Try the last release, please.
2016 -> I close this issue.

**Closed by emmanue1** 2019-05-22 11:54 UTC
