### ISSUE TITLE
JD-GUI 1.4.0 on Mac OS X 10.9.5 Crashes Entire System

### ISSUE THREAD

**Issue by kristianvld** [java-decompiler/jd-gui#125] opened 2016-05-05 13:33 UTC
Sometimes when viewing java code in .jar files the program suddenly crashes the whole machine. The whole machine freezes, you can not move the mouse, the keyboard stops responding and the system is in no way responding to any kind of input. The screen stays on and some processes continues to play like iTunes music. The only way to get the machine responding again is to do a hard restart, holding down the power button until the machine restarts.

I'm running this on a Macbook Pro Retina 10.9.5. I haven't been able to pinpoint to any exact action in the program that makes the machine crash as it seems quite random. I can be viewing a .java file, be scrolling down and suddenly it just freezes. I don't see any correlation to any background programs either, nor system stress such as high cpu nor high memory load. 

This never happens with any other program, only when working on inside JD-GUI. I have no clue as to what might be the cause of it. I can happily provide error logs or system stack traces if needed.

**Comment by jverne** [comment] 2016-05-05 15:47
Modern operating systems like OS X are unlikely to crash hard like this because of an application, especially a Java application that in turn is run inside a JVM. Userland processes like an active JVM running bytecode just don't have the access they need to hard crash on their own. It is things like device drivers and unexpected memory failures that lead to these sorts of problems, not userland applications.

This sounds like a hardware problem, or (depending on how Apple has tweaked the JVM) a problem with Java. Though the latter is unlikely. Though, you ought to make sure you have the latest Apple blessed JVM installed.

Without a crashlog (if one is actually written) we can't be sure what is going on. You should check in the usual locations for crashlog, just to be sure. Check the Apple docs for this, but it is somewhere in your ~/Library.

The reason you might be seeing this is because JD-GUI is a Java app that actually needs a fair amount of 64-bit address space for its heap and stack, and the JVM is making an allocation that is reaching bad memory.

If you have a way to reproduce this (but it seems you do not) you could "sample" the JVM running JD-GUI and see if it is always in the same place when it freezes.

**Comment by samrocketman** [comment] 2016-12-12 22:51
I recommend closing this issue.  It doesn't appear to have relevant details to reproduce and seems to mask a deeper problem on the machine which was affected.

**Closed** 2019-05-22 11:36 UTC
