### ISSUE TITLE
Add me as a maintainer?

### ISSUE THREAD

**Issue by samrocketman** [java-decompiler/jd-gui#188] opened 2017-10-01 20:18 UTC
Hi @emmanue1,
I would like to be added as a maintainer to JD-GUI so I could help the project grow and take some of the burden off of you.  Please give me ability to merge commits.

# Ways I can contribute:

* Reviewing community proposed PRs.
* Merging community proposed PRs.
* Adding i18n support for internationalization.
* Tagging releases.

# My background

I have several open source projects which I have created ([you can find them here][1]).

I also contribute regularly to the [Jenkins CI project][2] (see my contributions of [code][commits], opening [GitHub issues][issues]).  I contribute to Jenkins infrastructure through updating the Jenkins wiki and releasing plugins as a plugin maintainer.

I am the maintainer of the [GIMP][gimp] project [build system][gimp-ci].

[1]: https://github.com/samrocketman?utf8=%E2%9C%93&tab=repositories&q=&type=source
[2]: https://github.com/jenkinsci
[commits]: https://github.com/search?o=desc&q=org%3Ajenkinsci+author%3Asamrocketman&s=committer-date&type=Commits
[issues]: https://github.com/search?q=org%3Ajenkinsci+author%3Asamrocketman&type=Issues
[gimp]: https://www.gimp.org/
[gimp-ci]: https://build.gimp.org/

**Comment by uragan1987** [comment] 2017-10-14 10:57
looks like, no more support

**Comment by dodona2** [comment] 2017-10-14 12:26
the project seems to be dead -unfortunately.

**Comment by valentin616** [comment] 2017-10-15 14:10
@samrocketman You can fork the repository and merge pull quests to the forked repository.

**Comment by samrocketman** [comment] 2017-10-15 15:50
@valentin616 I'm aware; thank you.  Rather than creating a fork I'd rather revive the original if possible.

**Comment by dodona2** [comment] 2017-10-15 20:31
'Rather than creating a fork I'd rather revive the original if possible.'
thumbs up!!!

**Comment by theuserbl** [comment] 2017-10-19 20:47
@samrocketman You are right, that is better to revive the original. But if emmanue1 don't answer it is better to fork it and working on the fork, until he answers. After emanue1 answered, your fork can still be merged.

Also important is, to recreate the jd-core sources.
I have tried it with some little files at
https://github.com/theuserbl/jd-core-0.7.1
The problem is, that the decompilation of jd-core with an decompiler like jd, don't create working source code, because all decompilers have bugs.
An other point are things, decompiler don't know. If you have constants, the decompiler can't see, if in the sourcecode was a real number or the constant which represents it. So you have to do a lot of source recreation work.

**Comment by samrocketman** [comment] 2017-11-24 18:31
@java-decompiler see the subject 😄

**Comment by ghuls** [comment] 2018-01-23 10:53
@samrocketman Are you still planning to fork it?

The last activity of @emmanue1 on github was in 2015: https://github.com/emmanue1?tab=overview&from=2015-12-01&to=2015-12-31

https://plus.google.com/107508651694381167848
https://twitter.com/EmmanuelDupuy

**Comment by masl123** [comment] 2018-01-30 10:50
Last activity was Nov 24 2017:
Here: https://github.com/java-decompiler/jd-gui/issues/177

**Comment by samrocketman** [comment] 2018-01-30 10:54
@ghuls at this time, I don't have plans to fork it.  I have many projects under my wing at the moment.  My original intention was hopefully co-maintaining this project in the hopes that two people (or more) would be more active than one (or none).

**Comment by TheKalin** [comment] 2018-06-11 07:40
Does anyone know the most recent fork of this repo? Github   [network link](https://github.com/java-decompiler/jd-gui/network) couldn't handle the numbers ;<

**Comment by TheKalin** [comment] 2018-06-15 07:12
If you want to get the list of all the jd-gui forks you can use GitHub search with "jd-gui fork:true" filter.

**Comment by dodona2** [comment] 2018-06-15 08:22
there are a lot of forks, however all dead ends.

**Comment by TheKalin** [comment] 2018-06-15 08:27
@dodona2 yeah it looks like this.  Current repo owner is inactive.. so someone have to fork it. Any volunteers ? :)

**Comment by maxxyme** [comment] 2019-07-16 15:24
How do you explain this? https://github.com/java-decompiler/jd-gui/releases
JD-GUI 1.6.3 released July 13, 2019

**Comment by dodona2** [comment] 2019-07-16 17:12
> How do you explain this? https://github.com/java-decompiler/jd-gui/releases
> JD-GUI 1.6.3 released July 13, 2019

that's true. Thus we can close this issue.

**Comment by uragan1987** [comment] 2019-07-16 21:00
welcome back :)

**Closed** 2019-07-19 17:22 UTC
