### ISSUE TITLE
use jd-gui 1.4.0 Decompile  a class, but one of the methods is displayed as a byte code

### ISSUE THREAD

**Issue by oicq1699** [java-decompiler/jd-gui#86] opened 2015-10-06 08:35 UTC
**use jd-gui 0.3.6 decompile source code:**

```
  public boolean initServer()
  {
    boolean result = false;
    initServerLock.lock();
    try
    {
      if (systemStatus.getStatus() == 0) {
        result = true;
      }
      result = initServer(true);
    }
    finally
    {
      initServerLock.unlock();
    }
    return result;
  }
```

 **use jd-gui 1.4.0 decompile source code:**

```
/* Error */
  public boolean initServer()
  {
    // Byte code:
    //   0: iconst_0
    //   1: istore_1
    //   2: getstatic 60    gnnt/MEBS/timebargain/server/Server:initServerLock  Ljava/util/concurrent/locks/ReentrantLock;
    //   5: invokevirtual 485   java/util/concurrent/locks/ReentrantLock:lock   ()V
    //   8: getstatic 100   gnnt/MEBS/timebargain/server/Server:systemStatus    Lgnnt/MEBS/timebargain/server/model/SystemStatus;
    //   11: invokevirtual 182  gnnt/MEBS/timebargain/server/model/SystemStatus:getStatus   ()I
    //   14: ifne +5 -> 19
    //   17: iconst_1
    //   18: istore_1
    //   19: aload_0
    //   20: iconst_1
    //   21: invokevirtual 488  gnnt/MEBS/timebargain/server/Server:initServer  (Z)Z
    //   24: istore_1
    //   25: goto +12 -> 37
    //   28: astore_2
    //   29: getstatic 60   gnnt/MEBS/timebargain/server/Server:initServerLock  Ljava/util/concurrent/locks/ReentrantLock;
    //   32: invokevirtual 491  java/util/concurrent/locks/ReentrantLock:unlock ()V
    //   35: aload_2
    //   36: athrow
    //   37: getstatic 60   gnnt/MEBS/timebargain/server/Server:initServerLock  Ljava/util/concurrent/locks/ReentrantLock;
    //   40: invokevirtual 491  java/util/concurrent/locks/ReentrantLock:unlock ()V
    //   43: iload_1
    //   44: ireturn
    // Line number table:
    //   Java source line #490  -> byte code offset #0
    //   Java source line #491  -> byte code offset #2
    //   Java source line #494  -> byte code offset #8
    //   Java source line #495  -> byte code offset #17
    //   Java source line #497  -> byte code offset #19
    //   Java source line #498  -> byte code offset #28
    //   Java source line #499  -> byte code offset #29
    //   Java source line #500  -> byte code offset #35
    //   Java source line #499  -> byte code offset #37
    //   Java source line #501  -> byte code offset #43
    // Local variable table:
    //   start  length  slot    name    signature
    //   0  45  0   this    Server
    //   1  43  1   result  boolean
    //   28 8   2   localObject Object
    // Exception table:
    //   from   to  target  type
    //   8  28  28  finally
  }
```

**Comment by TehJumpingJawa** [comment] 2015-10-06 09:07
From what I've read here, jd apparently has known issues with try/finally blocks.

**Comment by oicq1699** [comment] 2015-10-06 09:37
I think you're right.

**Comment by samrocketman** [comment] 2015-10-06 15:34
May be related to #75.

**Comment by samrocketman** [comment] 2015-10-06 15:35
Duplicate of #37.

**Comment by emmanue1** [comment] 2015-10-06 16:04
Could you share your class to take a look ?

**Comment by oicq1699** [comment] 2015-10-07 09:34
I write simple class ,when use   finally keyword , This error will reappear 
**source code:**
```
public class TestJdError {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
			try{
				System.out.println("aaa");
			}catch(Exception ex){
				
				ex.printStackTrace();
				
			}finally{
				System.out.println("bbb");
			}
	}
```
**use jd-gui 1.4.0 decompile source code:**
```

public class TestJdError
{
  /* Error */
  public static void main(String[] args)
  {
    // Byte code:
    //   0: getstatic 16	java/lang/System:out	Ljava/io/PrintStream;
    //   3: ldc 22
    //   5: invokevirtual 24	java/io/PrintStream:println	(Ljava/lang/String;)V
    //   8: goto +30 -> 38
    //   11: astore_1
    //   12: aload_1
    //   13: invokevirtual 30	java/lang/Exception:printStackTrace	()V
    //   16: getstatic 16	java/lang/System:out	Ljava/io/PrintStream;
    //   19: ldc 35
    //   21: invokevirtual 24	java/io/PrintStream:println	(Ljava/lang/String;)V
    //   24: goto +22 -> 46
    //   27: astore_2
    //   28: getstatic 16	java/lang/System:out	Ljava/io/PrintStream;
    //   31: ldc 35
    //   33: invokevirtual 24	java/io/PrintStream:println	(Ljava/lang/String;)V
    //   36: aload_2
    //   37: athrow
    //   38: getstatic 16	java/lang/System:out	Ljava/io/PrintStream;
    //   41: ldc 35
    //   43: invokevirtual 24	java/io/PrintStream:println	(Ljava/lang/String;)V
    //   46: return
    // Line number table:
    //   Java source line #18	-> byte code offset #0
    //   Java source line #19	-> byte code offset #8
    //   Java source line #21	-> byte code offset #12
    //   Java source line #24	-> byte code offset #16
    //   Java source line #23	-> byte code offset #27
    //   Java source line #24	-> byte code offset #28
    //   Java source line #25	-> byte code offset #36
    //   Java source line #24	-> byte code offset #38
    //   Java source line #26	-> byte code offset #46
    // Local variable table:
    //   start	length	slot	name	signature
    //   0	47	0	args	String[]
    //   11	2	1	ex	Exception
    //   27	10	2	localObject	Object
    // Exception table:
    //   from	to	target	type
    //   0	8	11	java/lang/Exception
    //   0	16	27	finally
  }
}
```

**Comment by emmanue1** [comment] 2019-05-22 11:43
Try last release, please. 2015 -> I close this issue.

**Closed by emmanue1** 2019-05-22 11:43 UTC
